const { part1, part2 } = require("./solution")

describe("part1", () => {
  test("returns how many locations contain an antinode", () => {
    const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
    expect(part1(input)).toEqual(14)
  })
})

describe("part2", () => {
  test("returns how many locations contain an antinode with new model", () => {
    const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
    expect(part2(input)).toEqual(34)
  })
})
