const { part1, part2 } = require("./solution")

describe("part1", () => {
  test("returns how many distinct positions guard visits", () => {
    const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`
    expect(part1(input)).toEqual(41)
  })
})

describe("part2", () => {
  test("returns how many different positions you could obstruct guard at", () => {
    const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`
    expect(part2(input)).toEqual(6)
  })
})
