const { part1, part2 } = require("./solution")

describe("part1", () => {
  test("returns sum of shortest paths between all pairs of galaxies", () => {
    const input = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`
    expect(part1(input)).toEqual(374)
  })
})

describe("part2", () => {
  test("returns sum of shortest paths between all pairs of galaxies given specified gap", () => {
    const input = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`
    expect(part2(input, 10)).toEqual(1030)
    expect(part2(input, 100)).toEqual(8410)
  })
})
